sudo: required
services:
  - docker

script:
  - docker build -t lydianyu/node .
  - docker images lydianyu/node

before_deploy:
   - docker login -u <lydiatao> -p <Harvard170802!>

deploy:
  provider: script
  script: docker push lydiatao/node
  on:
    branch: master
